tasks:

  - name: terraform-and-kubectl-installation
    before: |
      source ./bin/install_terraform.sh
      source ./bin/set_terraform_cloud_token.sh
      source ./bin/install_kubectl.sh
      source ./bin/set_tf_alias.sh

  - name: azure-cli & docker login
    command: |
      sleep 60
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      source ./bin/set_tf_alias.sh
      az login --service-principal -u $IDE_CLIENT_ID -p $IDE_CLIENT_SECRET --tenant $IDE_TENANT_ID
      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
     
vscode:
  extensions:
    - hashicorp.terraform
