apiVersion: v1
kind: Pod
metadata:
  name: website-pod
  labels:
    app: website
spec:
  containers:
    - name: website-container
      image: ceeepath/my-website
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80