name: 'Cloud-DevOps-Assessment'

on:
  
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  environment_setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
    
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4

      - name: Install Docker
        uses: crazy-max/ghaction-setup-docker@v3
              
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ceeepath/my-website:latest .
          docker push ceeepath/my-website:latest
      
      - name: Install kubectl
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
         kubectl: '1.28.7'
         run: |
          kubectl version --client
                
      - name: Authenticate to AKS Cluster
        run: |
          mkdir ~/.kube
          touch ~/.kube/config
          ls ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          head -5 ~/.kube/config
          tail -5 ~/.kube/config